version: '3.5'
services:
  api1: # API - Instância 01
    build: .
    container_name: rinha-api1
    depends_on:
      - db
    expose:
      - "3000"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.25GB'

  api2: # API - Instância 01
    build: .
    container_name: rinha-api2
    depends_on:
      - db
    expose:
      - "3000"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.25GB'

  nginx:
    container_name: rinha-nginx
    image: nginx:alpine
    depends_on:
      - api1
      - api2
    ports:
        - "9999:9999"
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
          limits:
              cpus: '0.15'
              memory: '0.2GB'

  db: # Banco de dados
    image: postgres
    container_name: rinha-db
    hostname: rinha-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rinhadb
    ports:
      - "5432:5432"
    expose:
      - "5432"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '0.25GB'
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
    driver: local
networks:
  default:
    driver: bridge
    name: rinha