version: '3.5'
services:
  api1: &api 
    build: .
    container_name: rinha-api1
    hostname: rinha-api1
    restart: always
    environment:
      APP_PORT: 3000
    depends_on:
      - db
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.8GB'

  api2: 
    <<: *api
    container_name: rinha-api2
    hostname: rinha-api2
    environment:
      APP_PORT: 3001

  nginx:
    container_name: rinha-nginx
    image: nginx:alpine
    restart: always
    network_mode: host
    depends_on:
      - api1
      - api2
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
          limits:
              cpus: '0.10'
              memory: '0.1GB'

  db: # Banco de dados
    image: postgres
    container_name: rinha-db
    hostname: rinha-db
    restart: always
    network_mode: host
    command: postgres -c 'max_connections=450' -c 'log_error_verbosity=terse' -c 'effective_cache_size=512MB' -c 'shared_buffers=512MB'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rinhadb
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '1.3GB'
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
volumes:
  pg_data:
    driver: local